### ISSUE TITLE
Is working with VUSB?

### ISSUE THREAD

**Issue by tyrion9** [symbioquine/usb-hid-relay-java#1]
Do you check that working with VUSB?
http://vusb.wikidot.com/project:driver-less-usb-relays-hid-interface

**Comment by symbioquine** [comment]
No, I believe these two libraries apply to different kinds of USB relay controller boards and otherwise the projects have no connection.

* https://github.com/pavel-a/usb-relay-hid/blob/master/lib/usb_relay_hw.h#L4-L5
* https://github.com/symbioquine/usb-hid-relay-java/blob/master/src/main/java/net/symbioquine/usbhidrelay/UsbHidRelay.java#L42-L43
